version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"

    allow:
      - dependency-name: "com.googlecode.libphonenumber:libphonenumber"

    open-pull-requests-limit: 1