version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"

    # 🔥 1. libphonenumber만 감시
    allow:
      - dependency-name: "com.googlecode.libphonenumber:libphonenumber"

    # 🔥 2. PR 하나만 유지
    open-pull-requests-limit: 1

    # 🔥 3. 동일 PR 재사용 강제
    rebase-strategy: auto