name: libphonenumber CI

on:
  push:
    branches: [ main, master ]
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      -
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Read diff result
        id: diff
        run: |
          echo "CHANGED=$(grep -c 'added=' build/snapshot/diff.txt)" >> $GITHUB_ENV

      # 🔥 Slack 알림 (변경 있을 때만)
      - name: Slack notify
        if: false #env.CHANGED != '0'
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"🚨 libphonenumber 변경 감지\n$(cat build/snapshot/diff.txt)\"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      # 🔥 PR 자동 생성
      - name: Create Pull Request
        if: env.CHANGED != '0'
        uses: peter-evans/create-pull-request@v5
        with:
          title: "libphonenumber change detected"
          body: |
            자동 생성 PR
            변경 감지됨

            $(cat build/snapshot/diff.txt)
          branch: auto/libphonenumber-update

      # 🔥 CI fail gate (변경 있을 때 실패)
      - name: Fail CI if changed
        if: env.CHANGED != '0'
        run: exit 1